### ISSUE TITLE
Error:(1, 0) Expecting a stack map frame during grade sync

### ISSUE THREAD

**Issue by m-ivanov** [bluesliverx/gradle-android-publisher#6]
including `classpath 'com.savillians.gradle:android-publisher:0.4'` cause

```
Error:(1, 0) Expecting a stack map frame
Exception Details:
  Location:
    com/android/build/gradle/internal/TaskManager.getExtension()Lcom/android/build/gradle/BaseExtension; @5: aconst_null
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: 2ab4 005e b001 b0     
```

error during grade sync

**Comment by bluesliverx** [comment]
Looks like it's related to the latest gradle android plugin and the google publishing APIs.

https://github.com/googlesamples/android-play-publisher-api/issues/17

**Comment by bluesliverx** [comment]
@m-ivanov, try this:

```
classpath('com.savillians.gradle:android-publisher:0.4') {
  exclude module:'google-api-client'
}
```

Let me know if that helps and if it still works.

**Comment by m-ivanov** [comment]
thanks for fast response, yes it worked ,but during publication process complains about
 ```
Error:Execution failed for task ':app:androidPublish'.
> com/google/api/client/json/jackson2/JacksonFactory"
```

**Comment by bluesliverx** [comment]
In that case, try this.  I'm not able to try it right now, but hopefully it works as that's the latest version available of the google API client.

```
classpath('com.savillians.gradle:android-publisher:0.4') {
  exclude module:'google-api-client'
}
classpath 'com.google.api-client:google-api-client:1.20.0'
```

**Comment by m-ivanov** [comment]
Now work perfecly, great tool  
 ```
classpath('com.savillians.gradle:android-publisher:0.4') {
            exclude module:'google-api-client'
            exclude module:'com.google.apis'
        }
        classpath 'com.google.apis:google-api-services-androidpublisher:v2-rev16-1.20.0'
```

solved the problem , i don't know if ` exclude module:'google-api-client'` is relay required

**Comment by bluesliverx** [comment]
@m-ivanov, google-api-client is the one that does need to be excluded.  exclude module:'com.google.apis' actually does nothing since there is no module called 'com.google.apis'.  You could do exclude group:'com.google.apis', and that would be equivalent.

If you saw it work without the google.api.client exclusion, it is just gradle using the latest dependency instead of the older one since you are defining it manually.
